fixed bashisms

diff --git a/arxpdf b/arxpdf
--- a/arxpdf
+++ b/arxpdf
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-# arxpdf - Retrieve arXiV preprints as PDFs
+# arxpdf - Retrieve arXiv preprints as PDFs
 # Copyright (C) 2019 Matthew Kukla <matt.kukla@yandex.ru>
 
 # This program is free software: you can redistribute it and/or modify
@@ -20,68 +20,74 @@ VERSION=0.1.0
 URL=https://arxiv.org/pdf/
 
 usage(){
-echo 'Usage: arxpdf [arXiV id]... to download a PDF of [arXiV id]...'
-echo '       arxpdf [arXiV id]vn... to download the nth version of [arXiV id]'
+echo 'Usage: arxpdf [arXiv id]... to download a PDF of [arXiV id]...'
+echo '       arxpdf [arXiv id]vn... to download the nth version of [arXiV id]'
 echo
-echo 'arxpdf accepts both the old arXiV identifier format (subject.SC/YYMMNNN)'
+echo 'arxpdf accepts both the old arXiv identifier format (subject.SC/YYMMNNN)'
 echo 'and the current identifier format (YYMM.number).'
 echo
-echo 'For more about arXiV identifiers, see arxiv.org/help/arxiv_identifier'
+echo 'For more about arXiv identifiers, see arxiv.org/help/arxiv_identifier'
 echo
 echo 'Options:'
 echo '-h, --help        Show this message'
-echo '-v, --v           Show version number'
+echo '-v, --version           Show version number'
 exit
 }
 
 # Failure message for corrupt PDF
 fail_verify(){
-echo "[ERROR] Failed to download arXiV:$1 (invalid identifier or corrupt PDF)."
+echo "Error downloading arXiv:$1 (file corrupted)"
 }
 
 # Failure message for curl 
 fail_connect(){
-echo "[ERROR] Connection to the arXiV failed."
+echo "Error: connection to the arXiv failed"
 }
 
 # Check that the PDF isn't corrupt and has downloaded in its entirety 
 verify(){
-if [[ "$(tail "$1".pdf -n 1)"  != "%%EOF" ]]; then
-    fail_verify "$1"
-    rm "$1".pdf
+if [ "$(tail "$1".pdf -n 1)"  != "%%EOF" ]; then
+    fail_verify $1
+    rm $1.pdf
 fi
 }
 
+if [ $# = 0 ]; then
+    usage
+    exit 0
+fi    
 
 while [ "$#" -gt 0 ]; do
 # Download using current identifier format
-    if [[ $1 =~ ^[0-9]{4}\.[0-9]{5}(v[0-9]+)?$ ]]; then
-        if ! curl  $URL/"$1".pdf -o "$1.pdf" -s; then
+    if echo "$1" | grep '^[0-9]\{4\}\.[0-9]\{5\}\(v[0-9]\)\?$' -q ; then
+        if ! curl  $URL/$1.pdf -o $1.pdf -s; then
             fail_connect
         else
-            verify "$1"
+            verify $1
         fi    
         shift
 
 # Download using old identifier format
-    elif [[ $1 =~ ^.*\/[0-9]{7}(v[0-9]+)?$ ]]; then
+    elif echo $1 | grep '.\/[0-9]\{7\}\(v[0-9]\)\?$' -q; then
         FILE=$(printf '%s' "$1" | tr '/' '-')
-        if ! curl $URL/"$1".pdf -o "$FILE".pdf -s; then
+        if ! curl $URL/$1.pdf -o $FILE.pdf -s; then
             fail_connect
-        else    
-            verify "$FILE"
+        else   
+            verify $FILE
         fi    
         shift
-    
-    elif [[ $1 =~ ^-h|--help$ ]]; then
+
+    elif [ $1 = '--help' ] || [ $1 = '-h' ]; then       
         usage
+        exit
     
-    elif [[ $1 =~ ^-v|--version$ ]]; then
+    elif [ $1 = '--version' ] || [ $1 = '-v' ]; then
         echo $VERSION
         exit
 
     else 
         echo "Unknown option: $1"
+        usage
         exit 1
-    fi    
+    fi   
 done
